const h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
const expl = document.querySelector('#explanation');
console.log(expl);
console.dir(expl);
const hint = document.querySelector('.hint');
console.log(hint);
console.dir(hint);
const p = document.querySelectorAll('p');
console.log(p);
const link = document.querySelectorAll('.example-link');
console.log(link);
